service: my-service

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  region: eu-central-1
  
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/get
          method: get
plugins:
  - serverless-offline